name: Scan OCI Image using Grype
description: Scan OCI image for security vulnerabilities using Grype

inputs:
  image:
    description: 'The image to scan'
    required: true
  severity-cutoff:
    description: 'Severity cutoff level (negligible, low, medium, high, critical)'
    required: false
    default: 'critical'
  fail-build:
    description: 'Fail build on vulnerabilities'
    required: false
    default: 'true'
  github-username:
    description: 'The GitHub username to access container registry'
    required: false
    default: ''
  github-pat:
    description: 'The GitHub token to access container registry'
    required: false
    default: ''
  output-format:
    description: 'Output format (sarif, json, table, cyclonedx)'
    required: false
    default: 'sarif'

runs:
  using: composite
  steps:
    - name: Login to GitHub Container Registry
      if: ${{ inputs.github-pat != '' }}
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.github-username }}
        password: ${{ inputs.github-pat }}

    - name: Run Grype scan
      id: grype-scan
      uses: anchore/scan-action@v4
      with:
        image: ${{ inputs.image }}
        severity-cutoff: ${{ inputs.severity-cutoff }}
        fail-build: ${{ inputs.fail-build }}
        output-format: ${{ inputs.output-format }}

    - name: Upload SARIF to GitHub Security
      if: ${{ inputs.output-format == 'sarif' && always() }}
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: ${{ steps.grype-scan.outputs.sarif }}

    - name: Generate JSON for summary
      id: grype-json
      if: always()
      uses: anchore/scan-action@v4
      with:
        image: ${{ inputs.image }}
        severity-cutoff: ${{ inputs.severity-cutoff }}
        fail-build: 'false'
        output-format: json

    - name: Install gomplate
      if: always()
      shell: bash
      run: |
        curl -sSL https://github.com/hairyhenderson/gomplate/releases/download/v4.2.0/gomplate_linux-amd64 -o /usr/local/bin/gomplate
        chmod +x /usr/local/bin/gomplate

    - name: Generate scan summary
      if: always()
      shell: bash
      run: |
        JSON_FILE="${{ steps.grype-json.outputs.json }}"
        TEMPLATE_FILE="${{ github.action_path }}/template.md"

        if [ -f "$JSON_FILE" ]; then
          gomplate -c ".=$JSON_FILE" -f "$TEMPLATE_FILE" >> "$GITHUB_STEP_SUMMARY"
        else
          echo "## ⚠️ Scan results not available" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "**Image:** \`${{ inputs.image }}\`" >> "$GITHUB_STEP_SUMMARY"
          echo "**Severity Cutoff:** ${{ inputs.severity-cutoff }}" >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Sanitize image name for artifact
      if: always()
      id: sanitize
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.image }}"
        SAFE_NAME=$(echo "$IMAGE_NAME" | tr ':/' '-')
        echo "artifact-suffix=$SAFE_NAME" >> "$GITHUB_OUTPUT"

    - name: Upload scan results as artifact
      if: always()
      uses: actions/upload-artifact@v6
      with:
        name: grype-scan-${{ steps.sanitize.outputs.artifact-suffix }}-${{ github.run_id }}
        path: |
          ${{ steps.grype-scan.outputs.sarif }}
          ${{ steps.grype-scan.outputs.json }}
        retention-days: 90